package-lock.json, src/navigator/routes.tsx, src/pages/review/index.tsx, yarn.lock
DF-43
> 리뷰작성 api 연결
/review/:walkwayId로 라우팅 변경
=> [DF-43] 리뷰작성 api 연결

src/navigator/routes.tsx, src/pages/usingtrail/index.tsx, src/styles/BottomBarLayout.tsx
close:
- #DF-51
- 산책로 이용하기 화면구현
- 하단 네비바 안보이도록 설정
- 산책 중단 시 이용한 산책로 상세보기 페이지로 라우팅 설정
=> [DF-51]산책로 이용하기 페이지

src/components/newway_register/DateDisplay.tsx, src/components/newway_register/ToggleSwitch.tsx, src/components/newway_register/TrailInfo.tsx, src/navigator/routes.tsx, src/pages/review/index.tsx, src/pages/usingtrail/detail_using.tsx
close:
- #DF-52
- 이용한 산책로 상세 페이지 구현
- 특정 화면에서 깨지는 현상발생하여 반응형으로 구현
<image width=200px src="https://github.com/user-attachments/assets/51515cf5-d8f9-4bfa-838d-5452155f84e0"/>
- api 연동 후 리뷰페이지 라우팅 설정 다시 해야함
=> [DF-52] 이용한 산책로 상세 페이지 구현

src/components/newway_register/TrailInfo.tsx, src/pages/newway/index.tsx, src/pages/usingtrail/detail_using.tsx, src/pages/usingtrail/index.tsx
close:
- #DF-52
- 특정화면에서 깨지는 현상발견 후 반응형으로 코드 수정
- TrailInfo 코드 수정 후 newway와 usingtrail에 적용
=> [DF-52] 특정 화면에서 레이아웃 깨지는 현상 수정

src/pages/review/index.tsx
close:
- #DF-43
로컬 스토리지에 임시 저장해둔 개발 토큰을 쿠키에서 받아오도록 변경
=> [DF-43] 로컬스토리지에서 쿠키로 토큰 변경

src/pages/review/index.tsx
close:
- #DF-43
CORS  에러 발생 하여 쿠키 허용하는 코드 추가
=> [DF-43] 쿠키 전송 허용

src/apis/api.type.ts, src/apis/auth.ts, src/apis/auth.type.ts, src/apis/instance.ts, src/pages/mypage/index.tsx
close:
- #DF-54
- 마이페이지 유저 정보 조회 api 연동
=> 마이페이지 유저 정보 조회 api 연동

src/apis/review.ts, src/apis/review.type.ts, src/components/TrailReviewCard.tsx, src/pages/mypage/TrailReviewPage.tsx
close:
- #DF-44
-  작성한 리뷰 전체보기 api 연동
- "2024-12-25T14:55:17.642152"뜨는 날짜 포맷 변경 => "2024-12-25"
=> [DF-44] 작성한 리뷰 전체보기

src/navigator/routes.tsx, src/pages/index.tsx, src/styles/BottomBarLayout.tsx
close:
- #DF-60
- 임시 네비게이션 페이지 구현
=> feat(DF-60): 임시 네비게이션 페이지 구현

src/components/TrailReviewCard.tsx, src/navigator/routes.tsx, src/pages/mypage/TrailReviewPage.tsx, src/pages/review/ReviewCheck.tsx, src/pages/signin/index.tsx, src/pages/usingtrail/detail_using.tsx
close:
- #번호61
리뷰 확인하기 페이지 ui 제작 완료
=> feat : 리뷰 확인하기 페이지 ui 제작 완료

src/apis/api.type.ts, src/apis/trail.ts, src/components/TrailCardAll_View.tsx, src/pages/mypage/TrailListLikePage.tsx, src/pages/mypage/TrailListPage.tsx
close:
- #68
> 등록한 산책로 전체보기 api 연동 및  card ui 수정 진행했습니다.
=> feat : 등록한 산책로 전체보기 api 연동 및 card ui 수정

src/components/map/MainMap.tsx, src/components/map/TrackingMap.tsx, src/pages/newway/index.tsx
close:
- #DF-71
- 경로 좌표 반올림 로직 삭제
- 3초에 한 번씩 좌표 추가
- 트래킹 맵에 현재 위치 업데이트 버튼 추가
=> 경로 좌표 저장 로직 수정

src/components/map/PathMap.tsx, src/components/myregister/index.tsx, src/components/newway_register/InputField.tsx, src/pages/newway/registration.tsx
close:
- #DF-22
> 산책로 등록 페이지
- 산책로 작성 완료 버튼 클릭시, 등록완료 페이지
- 수정하기 버튼 클릭시, 수정 필드(채워진 상태)
- 수정완료 버튼 후 완료 페이지
<image width="200px" src="https://github.com/user-attachments/assets/6397b555-4da9-4b2b-a253-08becff03684"/>
<image width="200px" src="https://github.com/user-attachments/assets/a089b209-ac4b-4a47-ab22-534da4980bbe"/>
<image width="200px" src="https://github.com/user-attachments/assets/59c51934-da15-4e28-b3ac-d669f0c1ea97"/>
> 변경된 별점부분 ui는 추후 수정예정
산책로 등록 완료된 페이지(단건조회 페이지와 동일)에서 스크롤이 안되게 height설정을 하고 싶은데 잘 안되네요 ㅜ
=> 산책로 등록 페이지 완성

src/components/map/TrackingMapTest.tsx, src/hooks/useWatchLocation.ts, src/navigator/routes.tsx, src/pages/newway/NewwayTest.tsx, src/utils/calculateDistance.ts
close:
- #DF-75
- 트래킹 맵 test 페이지 추가
- 경로 추적을 위한 useWatchLocation 훅 구현
- 3초 간격으로 위치 정보 저장 로직 추가
=> [DF-75] 트래킹 맵 test 페이지

src/apis/review.ts, src/pages/review/ReviewCheck.tsx, src/pages/review/index.tsx, src/pages/splash/index.tsx
close:
- #번호
> 바뀐 api에 맞춰 코드 수정
url로 페이지 검색할 때 "/"로 리다이렉팅되서 토큰이 없을 때만 "/signin" 으로 이동하도록 수정하였습니다
=> 산책로 리뷰 내용보기 api 수정

package-lock.json, package.json, src/components/loading/WaveTextLoader.tsx, src/components/map/MainMap.tsx, src/pages/newway/NewwayTest.tsx, src/pages/splash/index.tsx, src/store/locationStore.type.ts, src/store/useLocationStore.ts, yarn.lock
close:
- #DF-81
- `main` 화면에 진입했을 때 현재 위치를 불러오는 시간을 줄이기 위해, 스플래시 화면에서 유저의 위치를 불러오는 플로우로 수정함
- 위치 정보 관리를 위한 `Zustand store` 구현
- `Zustand`를 선택한 이유: 현재 위치 정보라는 단순한 상태를 최소한의 설정으로 상태 관리가 가능하며, 번들 사이즈도 작음, 타입스크립트 지원
- `MainMap` 컴포넌트의 위치 정보 관리 로직 개선
- 저장된 위치 정보를 활용하여 초기 렌더링 최적화
- 위치 업데이트 버튼 클릭 시 전역 상태 업데이트 로직 추가
- 산책로 등록 페이지의 경우, 해당 페이지에 진입하기 전 업데이트 되지 않은 유저의 위치 변화가 있을 수 있기 때문에 저장한 위치를 사용하지 않음.
- 로딩 ux 개선을 위해 위치 로딩 컴포넌트 구현
=> [DF-81] 위치 정보 관리 최적화를 위한 Zustand 도입

src/apis/instance.ts, src/pages/splash/index.tsx
close:
- #DF-85
- 리프레시 수정 내용 이전으로 코드 되돌렸습니다.
=> 리프레시 수정 이전으로 되돌림

src/components/review/starCount.tsx
=> hotfix: 별 컴포넌트 위치이동

src/pages/detail/index.tsx, src/pages/main/index.tsx, src/pages/newway/index.tsx
close:
- #62 
- PathCard, 메인, 디테일 컴포넌트 거리 표시 방식 통일
- 등록/이용 페이지의 백버튼 클릭 함수 수정
=> [DF-89] PathCard, 메인, 디테일 컴포넌트 거리 표시 방식 통일

src/apis/review.ts, src/pages/mypage/index.tsx, src/pages/review/index.tsx
close:
- #번호
- 산책로 리뷰시 산책기록을 불러오지 못하던 문제 수정
=> hotfix(DF-84): 산책기록 state넘기기 수정

src/components/map/TrackingMap.tsx, src/pages/detail/index.tsx, src/pages/main/index.tsx, src/pages/newway/index.tsx, src/styles/colors/theme.ts
close:
- #61 
- 산책로 이용하기 ui 수정
- 산책로 이용하기 출발, 종점 표시
=> [DF-82] 산책로 이용하기 디자인 변경

src/components/loading/LoadingSpinner.tsx, src/pages/mypage/ReviewableHistory.tsx, src/pages/mypage/TrailListPage.tsx, src/pages/mypage/TrailReviewPage.tsx, src/pages/mypage/index.tsx, src/pages/review/ReviewCheck.tsx, yarn.lock
close:
- #DF-77
> 로딩 스피너 개발
https://github.com/user-attachments/assets/987bd4f6-53cc-4e56-bfb0-e47abc20a410
좀 짧아서 안보이는데 로딩 스피너 ui 구현했습니다
```
import LoadingSpinner from "src/components/loading/LoadingSpinner";
``` 
`<LoadingSpinner/>` 불러다가 사용하시면 됩니다 !
=> [DF-77] 로딩 스피너 제작

src/apis/review.ts, src/pages/mypage/ReviewableHistory.tsx, src/pages/mypage/TrailReviewPage.tsx, src/pages/mypage/index.tsx
close:
- #84
- 마이페이지에서 리뷰작성가능한 산책로 프리뷰
- '전체보기'-> 리뷰작성가능한 산책로 리스트 페이지
- 내가 작성한 리뷰 리스트 hasNext, lastId인식하도록 추가
=> [DF-84]리뷰가능한 산책로 목록페이지 api연동

src/apis/bookmark.ts, src/apis/bookmark.type.ts
close:
- #번호
`bookmark.type.ts` 와 `bookmark.ts` 파일만들어서 api연동 코드만 넣어놨습니다
=> [DF-69]북마크에 산책로 저장 및 삭제 axios코드

src/apis/bookmark.ts, src/components/bottomsheet/BookmarkContent.tsx
close:
- #DF-69
북마크에 산책로 저장하는 api연동
test페이지에 있는 바텀시트에 하드코딩으로 값만 넣어서 통신되는지 확인하였습니다. 추후에 북마크 아이콘을 눌러서 저장해도 큰 오류는 없을 거 같아요.
=> [DF-69]북마크에 산책로 저장

src/apis/instance.ts, src/components/button/GetTokenButton.tsx, src/pages/signin/index.tsx, src/pages/splash/index.tsx
close:
- #DF-91
- 개발 토큰 발급 버튼을 `signin/index.ts`에 추가함(개발 환경에서만 렌더링함)
- `instance.ts`, `splash/index.ts` 파일에서 토큰 발급, 갱신과 관련된 코드들을 모두 서버의 쿠키기반 토큰 관리, 갱신 로직에 맞추어 변경함
=> [DF-91] 개발 토큰 발급 버튼 추가, 변경된 토큰 관리 기획에 따라 인스턴스 수정

src/components/bottomsheet/BookmarkContent.tsx, src/pages/detail/index.tsx
=> feat : 북마크 바텀시트 제작

src/apis/likedWalkway.type.ts, src/apis/walkway.type.ts, src/pages/detail/index.tsx, src/pages/main/index.tsx
close:
- #번호
산책로 좋아요 로직이 날라가서 다시 추가했습니다 !
=> fix(DF-55): 하트토글 및 api연동 수정

src/apis/bookmark.ts, src/apis/bookmark.type.ts, src/components/bottomsheet/BookmarkContent.tsx, src/pages/detail/index.tsx, src/pages/test/index.tsx
=> fix : 바텀시트 수정

src/components/TrailReviewCard.tsx, src/components/bottomsheet/BookmarkContent.tsx, src/pages/detail/index.tsx, src/pages/mypage/TrailReviewPage.tsx, src/pages/mypage/index.tsx
close:
- #번호
- 북마크 저장시 토스트뜨도록 수정
- 마이페이지에서 리뷰보기 컴포넌트 클릭시 해당 산책로로 이동
- 리뷰 컴포넌트 ui 수정
북마크 저장및 삭제 시 뜨는 토스트 ui가 피그마 상으로는 다른데 따로 ui를 추가하는 방법이 있을까요? 아니면 크게 상관없으면 이대로 가도 괜찮을까요?
=> [QA] 리뷰컴포넌트 수정 및 토스트 추가

src/apis/bookmark.ts, src/apis/bookmark.type.ts, src/components/bottomsheet/BookmarkContent.tsx
=> fix : 북마크 선택시 ui 수정

src/hooks/useLocationPermission.ts, src/navigator/routes.tsx, src/pages/error/locationAcceptance.tsx, src/pages/splash/index.tsx, src/styles/colors/theme.ts
close:
- #DF-93
- 위치 정보 거부 경고 페이지 구현
- `useLocationPermission` 커스텀 훅 구현
- 권한 상태에 따라, 페이지 네비게이션 설정
=> [DF-93] 위치 정보 거부 경고 페이지 구현

src/pages/main/index.tsx
close:
- #DF-81
- 사용자 위치 데이터 설정이 스플래시 화면에 의존해 스플래시 화면을 거치지 않은 경우(직접 네비게이션 또는 새로고침을 통한 접근)는 위치가 업데이트되지 않아 사용자의 현재 위치가 제대로 표시되지 않는 문제가 발생힘. 
- 메인 컴포넌트에서 getCurrentLocation()을 호출하여 사용자의 현재 위치를 가져옴.
- Main 컴포넌트에 컴포넌트 마운트 시 한 번 실행되는 useEffect 추가하여, initializeLocation 함수 실행
- getCurrentLocation()을 호출하여 사용자의 현재 위치 가져오기
- 최신 좌표로 위치 스토어 업데이트
=> [DF-81] Main 페이지에 현재 위치 가져오는 함수 추가

src/apis/bookmark.ts, src/apis/review.ts, src/pages/mypage/TrailReviewPage.tsx, src/pages/review/ReviewCheck.tsx
close:
- #번호
- 특정 산책로 리뷰보기 api 응답 수정
- map 에러 수정
=> [DF-94]산책로 리뷰보기 api응답 수정

src/hooks/useLocationPermission.ts
close:
- #DF-92
- `/ `주소로 이동해도, 위치 접근 거부 페이지가 로딩되는 문제를 해결하기 위해 `useLocationPermission` 훅 수정
=> [DF-92] [QA] 위치 접근 허용 관련 훅 수정

src/components/bottomsheet/BookmarkContent.tsx, src/pages/detail/index.tsx
close:
- #번호
- 산책로 저장 및 삭제 api 구현
- checkbox 클릭으로 ui 변경
=> [DF-70]산책로 저장 및 삭제 구현

src/components/TrailReviewCard.tsx, src/pages/mypage/review/TrailReviewPage.tsx
close:
- #DF-96
- 리뷰 상세보기에서 작성날짜 없애기
=> [DF-96] 리뷰 상세보기에서 날짜 없애기

src/apis/bookmark.ts, src/apis/bookmark.type.ts, src/pages/detail/bookmark/components/BookmarkContent.tsx, src/pages/mypage/index.tsx, src/pages/mypage/trailList/TrailListPage.tsx
close:
- #DF-111
- 북마크 타이틀 조회 api 연동
=> [DF-111] 북마크 타이틀 조회 api 연동

src/apis/bookmark.ts, src/apis/bookmark.type.ts, src/pages/detail/bookmark/components/BookmarkContent.tsx, src/pages/mypage/index.tsx, src/pages/mypage/trailList/TrailListPage.tsx
=> 북마크 관련 수정사항 메인 머지

src/components/HistoryCardAll_View.tsx, src/components/TrailCard_mp.tsx, src/components/TrailReviewCard.tsx, src/components/appBar/index.tsx, src/components/bottomNavigation/index.tsx, src/components/bottomsheet/BottomSheet.tsx, src/components/map/MainMap.tsx, src/components/modal/ConfirmationModal.tsx, src/components/modal/Modal.tsx, src/components/newway_register/DateDisplay.tsx, src/components/newway_register/InputField.tsx, src/components/newway_register/ToggleSwitch.tsx, src/components/newway_register/TrailInfo.tsx, src/components/toast/ToastComponent.tsx, src/pages/detail/index.tsx, src/pages/main/header/components/SearchInput.tsx, src/pages/main/index.tsx, src/pages/mypage/review/ReviewableHistory.tsx, src/pages/mypage/review/TrailReviewPage.tsx, src/pages/mypage/trailList/TrailListPage.tsx, src/pages/newway/index.tsx, src/pages/newway/registration.tsx, src/pages/review/index.tsx, src/styles/GlobalStyles.tsx
close:
- #DF-112
- 태블렛 ui 반응형 처리
=> [DF-112] 태블렛 ui 반응형 작업

src/apis/crew/crew.ts, src/apis/crew/crew.type.ts, src/pages/community/detail/components/FeedList.tsx, src/pages/community/detail/components/FeedTogether.tsx, src/pages/community/detail/feed/index.tsx
close:
- #번호
- 크루 피드 api연동
- ui 수정
=> [DF-127] 크루 피드 api연동

src/apis/crew/crew.ts, src/apis/crew/crew.type.ts, src/pages/community/components/RecruitForm.tsx, src/pages/community/detail/components/MyCowalkList.tsx, src/pages/community/detail/components/RecruitList.tsx, src/pages/community/detail/together/index.tsx
close:
- #번호
> 같이 산책 api연동 및 ui 수정
- comment 관련 api 누락(디자인 누락으로 인한)
- 내가 신청한 목록보기 api없음
=> 위 사항 제외하고 개발 완료
=> [DF-128] 같이 산책 api연동

src/apis/crew/crew.ts, src/apis/crew/crew.type.ts, src/components/imageUpload/index.tsx, src/pages/community/detail/components/MyCowalkList.tsx, src/pages/community/detail/together/index.tsx, src/pages/community/info/index.tsx, src/pages/community/info/setting.tsx, src/pages/community/modify/index.tsx
close:
- #번호
> 크루 정보 수정 페이지 api연결
>크루장 이름은 api필드 추가 후 수정해야함
=> [DF-130]크루 정보 수정 api연동

src/apis/crew/crew.type.ts, src/pages/community/components/CustomDate.tsx, src/pages/community/components/CustomTime.tsx, src/pages/community/components/RecruitForm.tsx, src/pages/community/detail/components/MyCowalkList.tsx, src/pages/community/detail/together/detail.tsx, src/pages/community/detail/together/index.tsx, src/pages/community/info/setting.tsx
close:
- #번호
- 같이 산책 api에서 끝나는 시간 추가
- 해당 ui수정
- 토스트 추가
- 내가 신청한 산책일정 버튼 활성화 수정
=> [DF-132] 같이 산책 끝나는 시간 포함 수정

src/apis/crew/crew.ts, src/pages/community/create/index.tsx, src/pages/community/modify/index.tsx
close:
- #DF-137
- 크루명 중복 확인 api 페이로드에서 crewId 삭제
- 크루 생성, 수정 페이지에 수정사항 반영
=> [QA] 크루명 중복 확인 api 수정
